### ISSUE TITLE
1.20.1?

### ISSUE THREAD

**Issue by MechanosG** [enjarai/moderate-loading-screen#11]
Hiya.  Any plans on updating to 1.20.1+?  This is/was my favorite load screen to use in my modpacks.  Loaded fast, gave a quick preview of the included mods, has a nice enough color scheme out of the box, and is even compatible with the Memory Usage Screen mod.  But I'm thinking about moving from 1.19.4 to 1.20.1.  Would love to be able to include this mod again.

**Comment by enjarai** [comment]
Currently no updates of any kind are planned for this mod. I feel that it's a significant amount of effort to maintain for very little result, so I've shifted my focus to other mods.
