### ISSUE TITLE
Remove JIJ 

### ISSUE THREAD

**Issue by fzzyhmstrs** [enjarai/moderate-loading-screen#15]
This mod comes with "crash-pipe" JIJ. I have no idea why that would be needed or wanted on a loading screen mod. Please consider removing it and letting people that actually want to get jumpscared on crash install "crash-pipe" separately.

**Comment by enjarai** [comment]
I will be removing it in the next update, yes.

**Comment by IMB11** [comment]
You clearly dont understand why it's there, here's a good video on the psychology behind it: https://youtu.be/f8mL0_4GeV0?si=xESyEC_f3DUi3RP6

**Comment by enjarai** [comment]
Crash pipe has been removed with update 1.4.1.
