### ISSUE TITLE
[SUGGESTION] Test loading screen

### ISSUE THREAD

**Issue by srnyx** [enjarai/moderate-loading-screen#2]
A button in the config screen to test the loading screen.
*It can just reload resourcepacks as that shows it. Makes it so you don't have to navigate back to the mod's options when you want to quickly configure.*

**Comment by enjarai** [comment]
Added in 1.1.1. I couldn't figure out how to make it actually apply the new config when you press the button though, so for now you'll have to save manually for every change made.
